### ISSUE TITLE
Update Instructions For "Twelve Days" And Include Test Case To Prevent Reading File

### ISSUE THREAD

**Issue by RTurek** [exercism/ruby#1311]
# Overview

I think the spirit of the "Twelve Days" challenge implies that you should not just be reading and outputting the available text file [example of this](https://exercism.org/tracks/ruby/exercises/twelve-days/solutions/allcentury), you should be writing an algorithm that programmatically generates the song. The text file should just be available for the test runner to compare to the output of `TwelveDays.song`.

# TODO

- [ ] Update [Instructions.md](https://github.com/exercism/ruby/blob/main/exercises/practice/twelve-days/.docs/instructions.md)
  - [ ] to prompt the student with some more help to get started
  - [ ] Give some thought to the cultural unfamiliarity of this song - not everyone just "gets it" when seeing this for the first time
- [ ] Write [test](https://github.com/exercism/ruby/blob/main/exercises/practice/twelve-days/twelve_days_test.rb) to assert that the text file is not being read by the `TwelveDays` class
  - [ ] `expect File not_to receive :read` or something like that - not sure if this is possible. The test is a nice-to-have for me, I'm mostly interested in adding copy to the instructions that discourage the student from trying to just output the same exact file the test runner is using.

**Comment by RTurek** [comment]
```text
# Instructions

Your task in this exercise is to write a method that returns the lyrics of the song: 'The Twelve Days of Christmas'.

"The Twelve Days of Christmas" is a common Christmas carol. Each subsequent verse of the song builds on the previous verse.

Each verse of the song has several elements that are repeated from verse to verse. Identify these elements and try to re-use them when writing your code. Remember to be "DRY" (Don't Repeat Yourself)!

The lyrics your method returns should exactly match the text shown below.

# The Twelve Days Of Christmas
```text
On the first day of Christmas my true love gave to me: a Partridge in a Pear Tree.

On the second day of Christmas my true love gave to me: two Turtle Doves, and a Partridge in a Pear Tree.

On the third day of Christmas my true love gave to me: three French Hens, two Turtle Doves, and a Partridge in a Pear Tree.

On the fourth day of Christmas my true love gave to me: four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree.

On the fifth day of Christmas my true love gave to me: five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree.

On the sixth day of Christmas my true love gave to me: six Geese-a-Laying, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree.

On the seventh day of Christmas my true love gave to me: seven Swans-a-Swimming, six Geese-a-Laying, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree.

On the eighth day of Christmas my true love gave to me: eight Maids-a-Milking, seven Swans-a-Swimming, six Geese-a-Laying, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree.

On the ninth day of Christmas my true love gave to me: nine Ladies Dancing, eight Maids-a-Milking, seven Swans-a-Swimming, six Geese-a-Laying, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree.

On the tenth day of Christmas my true love gave to me: ten Lords-a-Leaping, nine Ladies Dancing, eight Maids-a-Milking, seven Swans-a-Swimming, six Geese-a-Laying, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree.

On the eleventh day of Christmas my true love gave to me: eleven Pipers Piping, ten Lords-a-Leaping, nine Ladies Dancing, eight Maids-a-Milking, seven Swans-a-Swimming, six Geese-a-Laying, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree.

On the twelfth day of Christmas my true love gave to me: twelve Drummers Drumming, eleven Pipers Piping, ten Lords-a-Leaping, nine Ladies Dancing, eight Maids-a-Milking, seven Swans-a-Swimming, six Geese-a-Laying, five Gold Rings, four Calling Birds, three French Hens, two Turtle Doves, and a Partridge in a Pear Tree.
```

```

**Comment by simonbacquie** [comment]
One idea I had was to add an extra test case, ensuring that the solution does not call any of the typical Ruby methods that would read from a file

**Comment by kotp** [comment]
Because Twelve Days exercise is not only for Ruby, these suggestions should be discussed in the problem-specifications repository, and so I am going to transfer this to there.
