### ISSUE TITLE
Checklist: normalise topics

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/ruby#958]
**Note**: the suggestions are generated automagically. If something is _actually_ missing, please open an issue at [problem-specifications](https://github.com/exercism/problem-specifications) to add the missing topics.

```
=> fetching config from ../exercism-ruby/config.json
=> reading topics from ..\problem-specifications\TOPICS.txt
```

<details>
  <summary>List of valid topics</summary>

- `abstract_classes`
- `algorithms`
- `arrays`
- `behavior_driven_development`
- `bitwise_operations`
- `booleans`
- `callbacks`
- `classes`
- `concurrency`
- `conditionals`
- `cryptography`
- `dates`
- `discriminated_unions`
- `domain_specific_languages`
- `enumerations`
- `equality`
- `events`
- `exception_handling`
- `files`
- `filtering`
- `floating_point_numbers`
- `functional_programming`
- `games`
- `generics`
- `globalization`
- `graphs`
- `inheritance`
- `integers`
- `interfaces`
- `lists`
- `logic`
- `loops`
- `maps`
- `math`
- `matrices`
- `memory_management`
- `networking`
- `object_oriented_programming`
- `operator_overloading`
- `optional_values`
- `parallelism`
- `parsing`
- `pattern_matching`
- `pattern_recognition`
- `performance`
- `polymorphism`
- `queues`
- `randomness`
- `reactive_programming`
- `records`
- `recursion`
- `refactoring`
- `regular_expressions`
- `searching`
- `security`
- `sequences`
- `sets`
- `sorting`
- `stacks`
- `strings`
- `structs`
- `test_driven_development`
- `text_formatting`
- `threading`
- `time`
- `transforming`
- `trees`
- `tuples`
- `type_conversion`
- `variables`
</details>

## Exercises with non-standard topics

- [ ] [`series`](https://github.com/exercism/ruby/tree/master/exercises/series)
  Incorrect topics:
  - [ ] `enumerable` (perhaps: `enumerations`)
- [ ] [`word-count`](https://github.com/exercism/ruby/tree/master/exercises/word-count)
  Incorrect topics:
  - [ ] `hash` (perhaps: `math`, `maps`, `dates`, `graphs`, `lists`, `sets`, `time`, `games`, `loops`, `arrays`, `classes`, `stacks`, `trees`, `files`, `logic`, `parsing`)
  - [ ] `enumerable` (perhaps: `enumerations`)
- [ ] [`resistor-color-duo`](https://github.com/exercism/ruby/tree/master/exercises/resistor-color-duo)
  Incorrect topics:
  - [ ] `array` (perhaps: `arrays`, `trees`, `loops`, `dates`, `graphs`, `lists`, `maps`, `sets`, `time`, `files`, `games`, `logic`, `math`, `parsing`)
- [ ] [`roman-numerals`](https://github.com/exercism/ruby/tree/master/exercises/roman-numerals)
  Incorrect topics:
  - [ ] `numbers` (perhaps: `integers`, `queues`, `tuples`, `games`, `dates`, `maps`, `sets`, `time`, `trees`, `files`)
- [ ] [`space-age`](https://github.com/exercism/ruby/tree/master/exercises/space-age)
  Incorrect topics:
  - [ ] `if_else_statements`
- [ ] [`say`](https://github.com/exercism/ruby/tree/master/exercises/say)
  Incorrect topics:
  - [ ] `numbers` (perhaps: `integers`, `queues`, `tuples`, `games`, `dates`, `maps`, `sets`, `time`, `trees`, `files`)
- [ ] [`queen-attack`](https://github.com/exercism/ruby/tree/master/exercises/queen-attack)
  Incorrect topics:
  - [ ] `errors` (perhaps: `arrays`, `events`, `loops`, `graphs`, `records`, `trees`, `generics`, `dates`, `lists`, `maps`, `queues`, `sets`, `stacks`, `strings`, `structs`, `tuples`, `files`, `games`)
- [ ] [`allergies`](https://github.com/exercism/ruby/tree/master/exercises/allergies)
  Incorrect topics:
  - [ ] `enumeration` (perhaps: `enumerations`)
- [ ] [`linked-list`](https://github.com/exercism/ruby/tree/master/exercises/linked-list)
  Incorrect topics:
  - [ ] `data_structure`
  - [ ] `pointer` (perhaps: `events`, `dates`, `integers`, `lists`, `time`, `files`)
- [ ] [`collatz-conjecture`](https://github.com/exercism/ruby/tree/master/exercises/collatz-conjecture)
  Incorrect topics:
  - [ ] `control_flow_loops` (perhaps: `loops`)
- [ ] [`zipper`](https://github.com/exercism/ruby/tree/master/exercises/zipper)
  Incorrect topics:
  - [ ] `data_structures`

## Exercises without topics

- [ ] [`binary`](https://github.com/exercism/ruby/tree/master/exercises/binary)
- [ ] [`trinary`](https://github.com/exercism/ruby/tree/master/exercises/trinary)
- [ ] [`hexadecimal`](https://github.com/exercism/ruby/tree/master/exercises/hexadecimal)
- [ ] [`octal`](https://github.com/exercism/ruby/tree/master/exercises/octal)
- [ ] [`point-mutations`](https://github.com/exercism/ruby/tree/master/exercises/point-mutations)

**Comment by kotp** [comment]
The `binary`, `trinary`, `hexadecimal`, and `octal` are deprecated, I believe, in favor of "All Your Base".  It may be fine to leave them without topics.

**Comment by SleeplessByte** [comment]
That's right. I have not removed them from the list.

**Comment by kytrinyx** [comment]
The topics have been deprecated in problem-specifications. We will be reevaluating topics for all exercises as part of implementing the concepts and concept exercises. I'm closing the issue.
